version: "3"

services:
  web:
    build: .
    container_name: livemeeting_web
    command: daphne -b 0.0.0.0 -p 8000 livemeeting.asgi:application
    volumes:
      - .:/app  # 调试阶段直接挂载代码
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:stable
    container_name: livemeeting_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /build/sslkey:/etc/ssl:ro
      - ./staticfiles:/app/staticfiles  # 生产阶段 collectstatic
    depends_on:
      - web
    restart: always
